"""inventory + disputes + card-tokenization

Revision ID: 27cc167e01b9
Revises: 300fd538ca77
Create Date: 2026-05-14 23:19:29.236683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27cc167e01b9'
down_revision: Union[str, Sequence[str], None] = '300fd538ca77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disputes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('importer_id', sa.String(length=64), nullable=False),
    sa.Column('exporter_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.String(length=40), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('refund_currency', sa.String(length=8), nullable=True),
    sa.Column('refund_tx_ref', sa.String(length=80), nullable=True),
    sa.Column('refund_payload', sa.Text(), nullable=True),
    sa.Column('replacement_order_id', sa.String(length=64), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['importer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disputes_exporter_id'), ['exporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disputes_importer_id'), ['importer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disputes_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disputes_status'), ['status'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('low_stock_threshold', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('last_inventory_update_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flw_card_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('flw_card_last4', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('flw_card_brand', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('last_renewal_attempt_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('renewal_failure_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('renewal_failure_count')
        batch_op.drop_column('last_renewal_attempt_at')
        batch_op.drop_column('flw_card_brand')
        batch_op.drop_column('flw_card_last4')
        batch_op.drop_column('flw_card_token')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('last_inventory_update_at')
        batch_op.drop_column('low_stock_threshold')
        batch_op.drop_column('stock_quantity')

    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disputes_status'))
        batch_op.drop_index(batch_op.f('ix_disputes_order_id'))
        batch_op.drop_index(batch_op.f('ix_disputes_importer_id'))
        batch_op.drop_index(batch_op.f('ix_disputes_exporter_id'))

    op.drop_table('disputes')
    # ### end Alembic commands ###
