"""init schema

Revision ID: 71ee465f49ac
Revises: 
Create Date: 2026-05-09 21:51:11.224873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ee465f49ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('paystack_code', sa.String(length=50), nullable=True),
    sa.Column('flutter_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('banks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banks_name'), ['name'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_category', sa.String(length=64), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('is_featured', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)

    op.create_table('exporter_plans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_subscription_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('annual_subscription_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('commission_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('product_promotion', sa.Integer(), nullable=False),
    sa.Column('max_product_promotion', sa.Integer(), nullable=False),
    sa.Column('max_market', sa.Integer(), nullable=False),
    sa.Column('max_store', sa.Integer(), nullable=False),
    sa.Column('max_store_per_market', sa.Integer(), nullable=False),
    sa.Column('max_product_per_store', sa.Integer(), nullable=False),
    sa.Column('max_product', sa.Integer(), nullable=False),
    sa.Column('support_priority_level', sa.String(length=8), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importer_plans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_subscription_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('annual_subscription_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('commission_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('product_limit', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logistics_companies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logistics_companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logistics_companies_name'), ['name'], unique=False)

    op.create_table('logistics_rates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('logistics_id', sa.String(length=64), nullable=False),
    sa.Column('origin_country', sa.String(length=100), nullable=False),
    sa.Column('destination_country', sa.String(length=100), nullable=False),
    sa.Column('base_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('per_kg_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logistics_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logistics_rates_logistics_id'), ['logistics_id'], unique=False)

    op.create_table('markets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('lga', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_markets_name'), ['name'], unique=False)

    op.create_table('notification_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('template', sa.String(length=80), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('to_address', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_logs_dedupe_key'), ['dedupe_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_notification_logs_template'), ['template'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_user_id'), ['user_id'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('middlename', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.String(length=20), nullable=True),
    sa.Column('profile_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('ethnicity', sa.String(length=50), nullable=True),
    sa.Column('valid_identification', sa.String(length=100), nullable=True),
    sa.Column('passport', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('kyc_status', sa.String(length=20), nullable=False),
    sa.Column('kyc_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('kyc_rejection_reason', sa.Text(), nullable=True),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('product_delivered', sa.Integer(), nullable=False),
    sa.Column('monthly_spent', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_period_start', sa.DateTime(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('business_profiles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('business_email', sa.String(length=255), nullable=True),
    sa.Column('business_address', sa.Text(), nullable=True),
    sa.Column('business_reg_number', sa.String(length=100), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('business_country', sa.String(length=100), nullable=True),
    sa.Column('annual_turnover', sa.String(length=50), nullable=True),
    sa.Column('duration_in_business', sa.Integer(), nullable=True),
    sa.Column('tin', sa.String(length=100), nullable=True),
    sa.Column('valid_identification', sa.String(length=100), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('bank_id', sa.String(length=64), nullable=True),
    sa.Column('account_name', sa.String(length=200), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('carts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('importer_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['importer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carts_importer_id'), ['importer_id'], unique=False)

    op.create_table('email_verification_tokens',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('order_number', sa.String(length=40), nullable=False),
    sa.Column('cart_id', sa.String(length=64), nullable=True),
    sa.Column('importer_id', sa.String(length=64), nullable=False),
    sa.Column('exporter_id', sa.String(length=64), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('logistics_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('shipping_mode', sa.String(length=20), nullable=False),
    sa.Column('logistics_id', sa.String(length=64), nullable=True),
    sa.Column('delivery_info', sa.Text(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['importer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_exporter_id'), ['exporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_importer_id'), ['importer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=True)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('importer_id', sa.String(length=64), nullable=False),
    sa.Column('exporter_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['importer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_exporter_id'), ['exporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_importer_id'), ['importer_id'], unique=False)

    op.create_table('shipping_addresses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipping_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipping_addresses_user_id'), ['user_id'], unique=False)

    op.create_table('stores',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('exporter_id', sa.String(length=64), nullable=False),
    sa.Column('market_id', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_exporter_id'), ['exporter_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('tx_ref', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_payload', sa.Text(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_tx_ref'), ['tx_ref'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('exporter_id', sa.String(length=64), nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.String(length=64), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('short_video_link', sa.Text(), nullable=True),
    sa.Column('min_order_quantity', sa.Integer(), nullable=False),
    sa.Column('max_order_quantity', sa.Integer(), nullable=False),
    sa.Column('properties', sa.Text(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('has_tax', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Integer(), nullable=False),
    sa.Column('promote', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['exporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_exporter_id'), ['exporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_product_name'), ['product_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_store_id'), ['store_id'], unique=False)

    op.create_table('cart_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('cart_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_items_cart_id'), ['cart_id'], unique=False)

    op.create_table('favourite_products',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_favourite_user_product')
    )
    with op.batch_alter_table('favourite_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favourite_products_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favourite_products_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourite_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favourite_products_user_id'))
        batch_op.drop_index(batch_op.f('ix_favourite_products_product_id'))

    op.drop_table('favourite_products')
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_items_cart_id'))

    op.drop_table('cart_items')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_store_id'))
        batch_op.drop_index(batch_op.f('ix_products_product_name'))
        batch_op.drop_index(batch_op.f('ix_products_exporter_id'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))

    op.drop_table('products')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_tx_ref'))
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))

    op.drop_table('payments')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_exporter_id'))

    op.drop_table('stores')
    with op.batch_alter_table('shipping_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipping_addresses_user_id'))

    op.drop_table('shipping_addresses')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_importer_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_exporter_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_code'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))
        batch_op.drop_index(batch_op.f('ix_orders_importer_id'))
        batch_op.drop_index(batch_op.f('ix_orders_exporter_id'))

    op.drop_table('orders')
    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_code'))

    op.drop_table('email_verification_tokens')
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carts_importer_id'))

    op.drop_table('carts')
    op.drop_table('business_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('support_tickets')
    op.drop_table('settings')
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_template'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_dedupe_key'))

    op.drop_table('notification_logs')
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_markets_name'))

    op.drop_table('markets')
    with op.batch_alter_table('logistics_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logistics_rates_logistics_id'))

    op.drop_table('logistics_rates')
    with op.batch_alter_table('logistics_companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logistics_companies_name'))

    op.drop_table('logistics_companies')
    op.drop_table('importer_plans')
    op.drop_table('exporter_plans')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))

    op.drop_table('categories')
    with op.batch_alter_table('banks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banks_name'))

    op.drop_table('banks')
    # ### end Alembic commands ###
